Eercise 1

In [10]:
import numpy as np

array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


Exercise 2

In [14]:
import numpy as np

liste= [3, 2, 0, 1, 2]

array =np.array(liste)
array_int = array.astype(int)

print(array_int)

[3 2 0 1 2]


Exercise 3

In [17]:
import numpy as np

array_3x3 = np.arange(1, 10).reshape(3, 3)

array_3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Exercise 4

In [18]:
import numpy as np

array_random = np.random.rand(4, 5)

array_random

array([[0.75757402, 0.98189436, 0.31995698, 0.86083836, 0.07351053],
       [0.97876319, 0.33959952, 0.59948357, 0.4416366 , 0.81519406],
       [0.48744669, 0.94286226, 0.46376938, 0.06014518, 0.47865264],
       [0.70890161, 0.72190935, 0.13466322, 0.54337198, 0.95128373]])

Exercise 5

In [19]:
import numpy as np

array = np.array([
    [21, 22, 23, 22, 22],
    [20, 21, 22, 23, 24],
    [21, 22, 23, 22, 22]
])

deuxieme_ligne = array[1]

deuxieme_ligne

array([20, 21, 22, 23, 24])

Exercise 6

In [20]:
import numpy as np

array = np.arange(10)

array_inverse = array[::-1]

array_inverse

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Exercise 7

In [21]:
import numpy as np

matrice_identite = np.eye(4)

matrice_identite

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Exercise 8

In [22]:
import numpy as np

array = np.arange(10)

somme = np.sum(array)

moyenne = np.mean(array)

print("Sum:", somme)
print("Average:", moyenne)

Sum: 45
Average: 4.5


Exercise 9

In [27]:
import numpy as np

array = np.arange(1, 21)

matrice = array.reshape(4, 5)

matrice

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

Exercise 10

In [28]:
import numpy as np

array = np.arange(10)

nombres_impairs = array[array % 2 != 0]

nombres_impairs

array([1, 3, 5, 7, 9])